/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fly;

/**
 *
 * @author ASUS
 */
public class CustomerFirstPage extends javax.swing.JFrame {

    /**
     * Creates new form CustomerFirstPage
     */
    public CustomerFirstPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PassengerTable = new javax.swing.JButton();
        NewCustomer = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        TicketBuying = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        PassengerTable.setBackground(new java.awt.Color(0, 255, 204));
        PassengerTable.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        PassengerTable.setText("Passenger Info");
        PassengerTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PassengerTableMouseClicked(evt);
            }
        });
        jPanel1.add(PassengerTable);
        PassengerTable.setBounds(510, 610, 390, 110);

        NewCustomer.setBackground(new java.awt.Color(0, 255, 204));
        NewCustomer.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        NewCustomer.setText("New Customer");
        NewCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                NewCustomerMouseClicked(evt);
            }
        });
        jPanel1.add(NewCustomer);
        NewCustomer.setBounds(510, 180, 390, 110);

        Update.setBackground(new java.awt.Color(0, 255, 204));
        Update.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        Update.setText("Update");
        Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UpdateMouseClicked(evt);
            }
        });
        jPanel1.add(Update);
        Update.setBounds(510, 330, 390, 110);

        TicketBuying.setBackground(new java.awt.Color(0, 255, 204));
        TicketBuying.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        TicketBuying.setText("Ticket Buying");
        TicketBuying.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TicketBuyingMouseClicked(evt);
            }
        });
        jPanel1.add(TicketBuying);
        TicketBuying.setBounds(510, 470, 390, 110);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fly/CustomerFirstPage.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1440, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PassengerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PassengerTableMouseClicked
        this.setVisible(false);
        PassengerInfoTable pit=new PassengerInfoTable();
        pit.setVisible(true);
    }//GEN-LAST:event_PassengerTableMouseClicked

    private void NewCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NewCustomerMouseClicked
        // TODO add your handling code here:
        NewCustomer nc=new NewCustomer();
        nc.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_NewCustomerMouseClicked

    private void UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdateMouseClicked

    private void TicketBuyingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TicketBuyingMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_TicketBuyingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerFirstPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerFirstPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NewCustomer;
    private javax.swing.JButton PassengerTable;
    private javax.swing.JButton TicketBuying;
    private javax.swing.JButton Update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
