package Fly;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class NewCustomer extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    public Statement state;
    public String query;
    public String Name;

    public NewCustomer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderBtn = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        NameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        EmailTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PhoneTxt = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        FemaleBtn = new javax.swing.JRadioButton();
        MaleBtn = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        NameTxt.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(NameTxt);
        NameTxt.setBounds(650, 310, 440, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setText("Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(420, 300, 220, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("E-Mail");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(420, 370, 220, 80);

        EmailTxt.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(EmailTxt);
        EmailTxt.setBounds(650, 380, 440, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("Phone");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(420, 440, 220, 80);

        PhoneTxt.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(PhoneTxt);
        PhoneTxt.setBounds(650, 450, 440, 50);

        AddBtn.setBackground(new java.awt.Color(51, 255, 51));
        AddBtn.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });
        jPanel2.add(AddBtn);
        AddBtn.setBounds(949, 540, 140, 60);

        BackBtn.setBackground(new java.awt.Color(255, 102, 0));
        BackBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BackBtn.setText("Back");
        BackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackBtnMouseClicked(evt);
            }
        });
        jPanel2.add(BackBtn);
        BackBtn.setBounds(40, 740, 120, 50);

        GenderBtn.add(FemaleBtn);
        FemaleBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        FemaleBtn.setText("Miss");
        jPanel2.add(FemaleBtn);
        FemaleBtn.setBounds(830, 240, 120, 50);

        GenderBtn.add(MaleBtn);
        MaleBtn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        MaleBtn.setText("Mr.");
        jPanel2.add(MaleBtn);
        MaleBtn.setBounds(650, 240, 120, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fly/CustomerFirstPage.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1440, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");  
             Connection conn = DriverManager  
                     .getConnection(  
                             "jdbc:sqlserver://localhost:1433;databaseName=FLY_SKY;selectMethod=cursor","sa", "123456");
             query="insert into PASSENGER(Name, Email, ContactNo)values(?,?,?)";
             PreparedStatement pst=conn.prepareStatement(query);
             if(MaleBtn.isSelected())
                 Name="Mr."+" " +NameTxt.getText();
             if(FemaleBtn.isSelected())
                 Name="Miss"+" " +NameTxt.getText();
             pst.setString(1, Name);
             pst.setString(2, EmailTxt.getText());
             pst.setString(3, PhoneTxt.getText());
             pst.executeUpdate();
             GenderBtn.clearSelection();
             NameTxt.setText(null);
             EmailTxt.setText(null);
             PhoneTxt.setText(null);
             JOptionPane.showMessageDialog(null, "Inserted Successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Insert Correctly");
        }
    }//GEN-LAST:event_AddBtnActionPerformed

    private void BackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackBtnMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        CustomerFirstPage cfp=new CustomerFirstPage();
        cfp.setVisible(true);
    }//GEN-LAST:event_BackBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JRadioButton FemaleBtn;
    private javax.swing.ButtonGroup GenderBtn;
    private javax.swing.JRadioButton MaleBtn;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
