/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fly;

/**
 *
 * @author ASUS
 */
public class NewEmployee extends javax.swing.JFrame {

    /**
     * Creates new form NewCustomer
     */
    public NewEmployee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        NameTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        NameTxt1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        NameTxt2 = new javax.swing.JTextField();
        MrCheck = new javax.swing.JCheckBox();
        MrCheck1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        NameTxt3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(null);

        NameTxt.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(NameTxt);
        NameTxt.setBounds(650, 310, 440, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel3.setText("Name");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(420, 300, 220, 80);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("E-Mail");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(420, 370, 220, 80);

        NameTxt1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(NameTxt1);
        NameTxt1.setBounds(650, 380, 440, 50);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel7.setText("Phone");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(420, 440, 220, 80);

        NameTxt2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(NameTxt2);
        NameTxt2.setBounds(650, 450, 440, 50);

        MrCheck.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        MrCheck.setText("Mrs.");
        jPanel2.add(MrCheck);
        MrCheck.setBounds(820, 260, 140, 40);

        MrCheck1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        MrCheck1.setText("Mr.");
        jPanel2.add(MrCheck1);
        MrCheck1.setBounds(650, 260, 140, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel4.setText("Employee ID");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(420, 180, 220, 80);

        NameTxt3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jPanel2.add(NameTxt3);
        NameTxt3.setBounds(650, 190, 440, 50);

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jButton1.setText("Add");
        jPanel2.add(jButton1);
        jButton1.setBounds(950, 600, 140, 60);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel8.setText("Password");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(420, 510, 220, 80);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(650, 520, 440, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fly/CompanyFirstPage.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(0, 0, 1440, 810);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1440, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewEmployee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox MrCheck;
    private javax.swing.JCheckBox MrCheck1;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField NameTxt1;
    private javax.swing.JTextField NameTxt2;
    private javax.swing.JTextField NameTxt3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
